### PR TITLE
Difference between kinto.js and kinto-client

### PR DESCRIPTION
**Pull request by Sayli-Karnik**

### CODE REVIEW

**Comment by leplatrem** [comment]
Excellent! Thank you! I find this explanation very concise and clear!

Do you think we should say `kinto-client.js`? Should we note somewhere that we will eventually have to rename `kinto.js` to something like `kinto-offline.js`? (*Those are genuine questions ;)*)

Thanks again!

**Comment by Sayli-Karnik** [comment]
Ok so I should write kinto-client.js instead of just kinto-client? 
And should I add a line at the end mentioning the renaming to kinto-offline.js part?

**Comment by leplatrem** [comment]
> Ok so I should write kinto-client.js instead of just kinto-client? 

yes please!

> should I add a line at the end mentioning the renaming to kinto-offline.js part?

well, I don't know, it was just an idea :) if we're not sure, let's leave it like that

**Comment by Sayli-Karnik** [comment]
Are there any other changes required?

**Comment by leplatrem** [comment]
I think we're good! 

A big thank you!

**Pull request merged**
